NotificationChannelRequest Builder | NotificationRequest Builder #141
thudugala/Plugin.LocalNotification pull request #142
Opened 2021-02-14 07:46 UTC by ArunPrakashG

### What does this PR do?
Implement basic fluent pattern for creating a NotificationChannel and a NotificationRequest.
Also adds a boolean value for BypassDND option.

##### Why are we doing this? Any context or related work?
For this opened issue #141

2021-03-06 13:55 UTC, ArunPrakashG commented
UPDATE: Added Fluent builder for AndroidOptions & iOSOptions,
Added a better way to create the builder on Show(...)

2021-03-14 06:43 UTC, ArunPrakashG commented
@thudugala  Hi, could you please review this PR ?

2021-03-14 06:47 UTC, thudugala commented
@ArunPrakashG It is in review. Please go through the review comments.

2021-03-14 07:03 UTC, ArunPrakashG commented
I am sorry to ask this, but this is my first pull request, review comments as in, are there any marked on the files itself ? I viewed the changed files through github itself and couldn't find any.

I just removed a test function which i added accidently.

2021-03-14 07:55 UTC, thudugala requested changes
Please rename CanBypassDND to CanBypassDnd

2021-03-14 09:08 UTC, ArunPrakashG commented
Done!

2021-03-14 09:27 UTC, thudugala approved these changes

2021-03-14 09:27 UTC, merged